helmDefaults:
  wait: true
  timeout: 600
  createNamespace: true

environments:
  dev:
    values:
      - ./env/dev/values.yaml
      - ./env/dev/proxy.values.yaml
    secrets:
      - ./env/dev/secrets.sops.yaml
  prod:
    values:
      - ./env/prod/values.yaml
    secrets:
      - ./env/prod/secrets.sops.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: ory
    url: https://k8s.ory.sh/helm/charts
  - name: raw
    url: https://bedag.github.io/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: cnpg-grafana
    url: https://cloudnative-pg.github.io/grafana-dashboards

---

releases:


  #  ensure the namespaces exist, case we add to it then create it later
  - name: create-namespaces
    namespace: kube-system
    chart: raw/raw
    version: 2.0.2
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: networking


  - name: kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    labels:
      app: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "~65.0.0"
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./values/kube-prometheus-stack.yaml.gotmpl


  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "~1.19.0"
    set:
      - name: crds.enabled
        value: true
    values:
      # dns to use for the dns-01 challenge isn't resolving, this helps
      - extraArgs:
          - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
          - --dns01-recursive-nameservers-only


  - name: certificates
    namespace: cert-manager
    chart: ./charts/certificates
    needs:
      - cert-manager/cert-manager
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./env/{{ .Environment.Name }}/values.yaml
      - ./charts/certificates/values.yaml

  - name: traefik
    namespace: networking
    chart: traefik/traefik
    version: "~37.4.0"
    needs:
        - cert-manager/certificates
    values:
      - ./values/traefik.yaml.gotmpl

  - name: traefik-routes
    namespace: networking
    chart: ./charts/traefik
    needs:
      - networking/traefik
    values:
      - ./env/{{ .Environment.Name }}/values.yaml

  - name: cnpg-grafana
    namespace: monitoring
    chart: cnpg-grafana/cluster
    version: "0.0.5"

  - name: cnpg-operator
    namespace: database
    chart: cnpg/cloudnative-pg
    version: "~0.26.1"
    set:
      - name: crds.create
        value: true

  - name: postgres
    namespace: database
    chart: ./charts/postgres
    needs:
      - database/cnpg-operator
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./env/{{ .Environment.Name }}/values.yaml
      - ./env/{{ .Environment.Name }}/proxy.values.yaml

  - name: postgres-cluster
    namespace: database
    chart: cnpg/cluster
    version: "~0.3.1"
    needs:
      - database/cnpg-operator
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./env/{{ .Environment.Name }}/values.yaml
      - ./values/postgres-cluster.yaml.gotmpl

  - name: mailhog
    namespace: tools
    chart: ./charts/mailhog
    needs:
      - networking/traefik-routes
    values:
      - ./charts/mailhog/values.yaml.gotmpl



  - name: kratos
    namespace: ory
    chart: ory/kratos
    version: "~0.58.0"
    needs:
      - database/postgres-cluster
      - tools/mailhog
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./env/{{ .Environment.Name }}/values.yaml
      - ./values/kratos.yaml.gotmpl


  - name: application
    namespace: application
    chart: ./charts/application
    needs:
      - networking/traefik-routes
      - database/postgres-cluster
    secrets:
      - ./env/{{ .Environment.Name }}/secrets.sops.yaml
    values:
      - ./env/{{ .Environment.Name }}/values.yaml
      - ./env/{{ .Environment.Name }}/proxy.values.yaml