{{- range $name, $password := .Values.env.secrets.postgres.passwords }}

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database-{{ $name }}
  namespace: database
spec:
  name: {{ $name }}
  owner: {{ $name }}
  ensure: present
  cluster:
    name: postgres-cluster

---
{{-  end }}