
apiVersion: v1
kind: Secret
type:  kubernetes.io/basic-auth
metadata:
    name: postgres-cluster-superuser
    namespace:  "database"
    labels:
      cnpg.io/reload: "true"
stringData:
    dbname: "*"
    fqdn-jdbc-uri: "jdbc:postgresql://postgres-cluster-rw.database.svc.cluster.local:5432/*?password={{ .Values.env.secrets.postgres.superuser.password }}&user={{ .Values.env.postgres.superuser.name }}"
    fqdn-uri: "postgresql://{{ .Values.env.postgres.superuser.name }}:{{ .Values.env.secrets.postgres.superuser.password }}@postgres-cluster-rw.database.svc.cluster.local:5432/*"
    host: "postgres-cluster-rw"
    jdbc-uri: "jdbc:postgresql://postgres-cluster-rw.database:5432/*?password={{ .Values.env.secrets.postgres.superuser.password }}&user={{ .Values.env.postgres.superuser.name }}"
    pgpass: "postgres-cluster-rw:5432:*:{{ .Values.env.postgres.superuser.name }}:{{ .Values.env.secrets.postgres.superuser.password }}"
    port: "5432"
    uri: "postgresql://{{ .Values.env.postgres.superuser.name }}:{{ .Values.env.secrets.postgres.superuser.password }}@postgres-cluster-rw.database:5432/*"
    user: {{ .Values.env.postgres.superuser.name | quote }}
    username: {{ .Values.env.postgres.superuser.name | quote }}
    password: {{ .Values.env.secrets.postgres.superuser.password | quote }}

---

{{- range $name, $password := .Values.env.secrets.postgres.passwords }}

apiVersion: v1
kind: Secret
type:  kubernetes.io/basic-auth
metadata:
    name: postgres-cluster-{{ $name }}
    namespace:  "database"
    labels:
      cnpg.io/reload: "true"
stringData:
    username: {{ $name | quote }}
    password: {{ $password | quote }}

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database-{{ $name }}
  namespace: database
spec:
  name: {{ $name }}
  owner: {{ $name }}
  ensure: present
  cluster:
    name: postgres-cluster

---
{{-  end }}
