{{- if .Values.env.secrets.traefik.basicauth }}
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-basicauth
  namespace: networking
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  users: |
    {{- range $username, $hash := .Values.env.secrets.traefik.basicauth }}
    {{ $username }}:{{ $hash }}
    {{- end }}
{{- end }}
