{
 "title": "Compass/Cert-Manager",
 "description": "The dashboard gives an overview of the SSL certs managed by cert-manager in Kubernetes",
 "tags": [
  "k8s",
  "cert-manager"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Valid Certificates",
   "type": "stat",
   "description": "The number if available certificates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expiring Certificates",
   "type": "stat",
   "description": "The number of certificates that will expire within the next 14 days",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} < (time()+(14*24*3600)))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Total ACME Requests",
   "type": "stat",
   "description": "Total number of HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "bargauge",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time to Automatic Renewal",
   "type": "bargauge",
   "description": "Time before the certificates are automatically renewed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(certmanager_certificate_renewal_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "timeseries",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}